usr/share/doc/minetest
usr/share/games/minetest/builtin
usr/share/games/minetest/client
usr/share/games/minetest/fonts
usr/share/games/minetest/games
usr/share/games/minetest/textures
usr/share/icons/hicolor/128x128/apps/minetest.png
usr/share/icons/hicolor/scalable/apps/minetest.svg
usr/share/locale
usr/share/metainfo/net.minetest.minetest.appdata.xml usr/share/metainfo/
src/unittest/test_world/world.mt usr/share/games/minetest/autopkgtest/test_world
src/unittest/test_mod/test_mod usr/share/games/minetest/autopkgtest/test_mod
